default:
  parent: "syn20400157"
  path_to_markdown: "inst/using-the-dccvalidator-app-amp-ad.Rmd"
  study_table: "syn11363298"
  annotations_table: "syn10242922"
  annotations_link: "https://shinypro.synapse.org/users/nsanati/annotationUI/"
  templates_link: "https://www.synapse.org/#!Synapse:syn18512044"
  study_link_animal: "https://adknowledgeportal.synapse.org/#/Explore/Studies?Study=syn8391648"
  study_link_human: "https://adknowledgeportal.synapse.org/#/Explore/Studies?Study=syn3159438"
  study_link_ref: ""
  teams:
    - "273957"
  templates:
    manifest_template: "syn20820080"
    individual_templates:
      human: "syn12973254"
      mouse or other animal model: "syn12973253"
    biospecimen_templates:
      mouse or other animal model: "syn12973252"
      human: "syn12973252"
      drosophila: "syn20673251"
    assay_templates:
      rnaSeq: "syn12973256"
  species_list:
    - "mouse or other animal model"
    - "human"
    - "drosophila"
  complete_columns:
    manifest:
      - "parent"
      - "path"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"
  contact_email: "karawoo@synapse.org"

amp-ad:
  parent: "syn21643404"
  annotations_table:
    - "syn10242922"
    - "syn21459391"
  annotations_link: "https://shinypro.synapse.org/users/kwoo/amp-ad-metadata-dictionary/"
  teams:
    - "3320424"
    - "3405451"
  study_link_ref: "https://adknowledgeportal.synapse.org/#/DataAccess/AcknowledgementStatements"
  species_list:
    - "human"
    - "drosophila"
    - "MODEL-AD mouse model"
    - "other mouse or animal model"
  templates:
    individual_templates:
      human: "syn12973254"
      other mouse or animal model: "syn12973253"
      MODEL-AD mouse model: "syn21084071"
    assay_templates:
      proteomics: "syn12973255"
      single cell RNAseq: "syn21018360"
      wholeGenomeSeq: "syn21018358"
      wholeExomeSeq: "syn21078272"
      NanoString: "syn21082744"
      snpArray: "syn21372586"
      TMT quantitation: "syn21433357"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
      - "path"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"

pec:
  parent: "syn21763123"
  path_to_markdown: "inst/using-the-dccvalidator-pec.Rmd"
  study_table: "syn20968992"
  annotations_table: "syn20981788"
  annotations_link: "https://www.synapse.org/#!Synapse:syn20729790"
  templates_link: "https://www.synapse.org/#!Synapse:syn20729790"
  study_link_animal: "https://www.synapse.org/#!Synapse:syn4566132"
  study_link_human: "https://www.synapse.org/#!Synapse:syn4590909"
  teams:
    - "3323356"
  templates:
    manifest_template: "syn20782058"
    individual_templates:
      human: "syn20781820"
      animal: "syn21053116"
    biospecimen_templates:
      animal model: "syn20768131"
      human: "syn20768131"
    assay_templates:
      wholeGenomeSeq: "syn20980993"
      rnaSeq: "syn20768650"
      ATACSeq: "syn20768526"
      TMT quantitation: "syn21680761"
      HI-C: "syn21680758"
      snpArray: "syn21680759"
      ChIPSeq: "syn21861858"
  species_list:
    - "human"
    - "animal model"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
      - "path"
    individual:
      - "individualID"
      - "individualIdSource"
      - "species"
      - "reportedGender"
      - "postmortem"
      - "primaryDiagnosis"
    biospecimen:
      - "individualID"
      - "specimenID"
      - "organ"
      - "tissue"
      - "nucleicAcidSource"
    assay:
      - "specimenID"
      - "platform"
      - "libraryPrep"
      - "libraryPreparationMethod"
      - "runType"
  contact_email: "kelsey@synapse.org"

annotations-research:
  parent: "syn21782020"
  annotations_table:
    - "syn10242922"
    - "syn21459391"
  annotations_link: "https://shinypro.synapse.org/users/kwoo/amp-ad-metadata-dictionary/"
  teams:
    - "3407020"
    - "273957"
  study_link_ref: "https://adknowledgeportal.synapse.org/#/DataAccess/AcknowledgementStatements"
  templates:
    assay_templates:
      proteomics: "syn12973255"
      single cell RNAseq: "syn21018360"
      wholeGenomeSeq: "syn21018358"
      wholeExomeSeq: "syn21078272"
      NanoString: "syn21082744"
      snpArray: "syn21372586"
      TMT quantitation: "syn21433357"
  complete_columns:
    manifest:
      - "consortium"
      - "study"
      - "grant"
      - "fileFormat"
      - "parent"
      - "path"
    individual:
      - "individualID"
    biospecimen:
      - "individualID"
      - "specimenID"
    assay:
      - "specimenID"
